spring:
  # Test Database Configuration (H2 in-memory)
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  # JPA Configuration for Testing
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  # Redis Configuration for Testing (embedded)
  redis:
    host: localhost
    port: 6370
    database: 15
  
  # RabbitMQ Configuration for Testing
  rabbitmq:
    host: localhost
    port: 5673
    username: test
    password: test

# Logging Configuration for Testing
logging:
  level:
    com.gitlab.metrics: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.test: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Test specific settings
gitlab:
  webhook:
    secret: test-webhook-secret
  api:
    rate-limit:
      enabled: false