server:
  port: 8080

spring:
  application:
    name: gitlab-metrics-backend
  
  profiles:
    active: simple
  
  # Database Configuration - 使用内存数据库进行测试
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  # H2 Console (for testing)
  h2:
    console:
      enabled: true
      path: /h2-console

# Logging Configuration
logging:
  level:
    com.gitlab.metrics: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Application Specific Configuration
app:
  performance:
    batch-size: 100
    async-core-pool-size: 2
    async-max-pool-size: 5
    async-queue-capacity: 50
    query-timeout: 30