server:
  # HTTPS/SSL Configuration
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: ${SSL_KEYSTORE_PASSWORD:changeit}
    key-store-type: PKCS12
    key-alias: gitlab-metrics
    protocol: TLS
    enabled-protocols: TLSv1.2,TLSv1.3
    ciphers: TLS_AES_256_GCM_SHA384,TLS_CHACHA20_POLY1305_SHA256,TLS_AES_128_GCM_SHA256,ECDHE-RSA-AES256-GCM-SHA384,ECDHE-RSA-AES128-GCM-SHA256
  port: 8443
  http:
    port: 8080

spring:
  # Production Database Configuration with SSL
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/gitlab_metrics?useSSL=true&requireSSL=true&verifyServerCertificate=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC}
    username: ${DATABASE_USERNAME:gitlab_metrics}
    password: ${DATABASE_PASSWORD:password}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
      # SSL相关配置
      data-source-properties:
        useSSL: true
        requireSSL: true
        verifyServerCertificate: true
        trustCertificateKeyStoreUrl: ${DB_TRUST_STORE_URL:}
        trustCertificateKeyStorePassword: ${DB_TRUST_STORE_PASSWORD:}
        clientCertificateKeyStoreUrl: ${DB_CLIENT_CERT_URL:}
        clientCertificateKeyStorePassword: ${DB_CLIENT_CERT_PASSWORD:}
  
  # JPA Configuration for Production
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        jdbc:
          batch_size: 50
  
  # Redis Configuration for Production
  redis:
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 2
  
  # RabbitMQ Configuration for Production
  rabbitmq:
    listener:
      simple:
        concurrency: 10
        max-concurrency: 20

# Logging Configuration for Production
logging:
  level:
    com.gitlab.metrics: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  file:
    name: logs/gitlab-metrics.log
    max-size: 100MB
    max-history: 30

# Production specific settings
gitlab:
  api:
    rate-limit:
      enabled: true
      requests-per-minute: 500

# Cache Configuration for Production
cache:
  redis:
    default-ttl: 7200
    metrics-ttl: 3600

# Application Security Configuration
app:
  security:
    # AES加密密钥 (生产环境应从环境变量获取)
    encryption:
      key: ${ENCRYPTION_KEY:}
    # JWT配置
    jwt:
      secret: ${JWT_SECRET:}
      expiration: 86400000 # 24小时
    # CORS配置
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:https://localhost:3000}
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true