server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

spring:
  application:
    name: gitlab-metrics-backend
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  # Database Configuration
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/gitlab_metrics?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:20}
      minimum-idle: ${HIKARI_MIN_IDLE:5}
      idle-timeout: ${HIKARI_IDLE_TIMEOUT:300000}
      connection-timeout: ${HIKARI_CONNECTION_TIMEOUT:20000}
      max-lifetime: ${HIKARI_MAX_LIFETIME:1200000}
      leak-detection-threshold: ${HIKARI_LEAK_DETECTION:60000}
      # Performance optimizations
      auto-commit: false
      connection-test-query: SELECT 1
      validation-timeout: 5000
      # Connection pool name for monitoring
      pool-name: GitLabMetricsCP
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
        # Performance optimizations
        jdbc:
          batch_size: ${HIBERNATE_BATCH_SIZE:50}
          batch_versioned_data: true
          fetch_size: ${HIBERNATE_FETCH_SIZE:100}
        order_inserts: true
        order_updates: true
        # Second level cache
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        # Connection handling
        connection:
          provider_disables_autocommit: true
        # Query optimization
        query:
          plan_cache_max_size: 2048
          plan_parameter_metadata_max_size: 128
        # Statistics
        generate_statistics: ${HIBERNATE_STATISTICS:false}
  
  # Redis Configuration
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: ${REDIS_DATABASE:0}
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
  
  # RabbitMQ Configuration
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:admin}
    virtual-host: ${RABBITMQ_VHOST:/}
    connection-timeout: 15000
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 2
  
  # Jackson Configuration
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,configprops,beans,threaddump,heapdump
      base-path: /actuator
      cors:
        allowed-origins: "*"
        allowed-methods: GET,POST
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
      probes:
        enabled: true
    info:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
    env:
      show-values: when-authorized
  health:
    circuitbreakers:
      enabled: true
    diskspace:
      enabled: true
      threshold: 10MB
    redis:
      enabled: true
    db:
      enabled: true
    rabbit:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: 30s
    distribution:
      percentiles-histogram:
        http.server.requests: true
        webhook.processing.duration: true
        commits.analysis.duration: true
      percentiles:
        http.server.requests: 0.5,0.95,0.99
        webhook.processing.duration: 0.5,0.95,0.99
    tags:
      application: gitlab-metrics-backend
      environment: ${spring.profiles.active}
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

# Logging Configuration
logging:
  level:
    com.gitlab.metrics: ${LOG_LEVEL:INFO}
    org.springframework.security: ${SECURITY_LOG_LEVEL:WARN}
    org.hibernate.SQL: ${SQL_LOG_LEVEL:WARN}
    org.hibernate.type.descriptor.sql.BasicBinder: ${SQL_PARAM_LOG_LEVEL:WARN}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Application Specific Configuration
gitlab:
  webhook:
    secret: ${GITLAB_WEBHOOK_SECRET:your-webhook-secret}
    timeout: 5000
  api:
    rate-limit:
      enabled: true
      requests-per-minute: 1000

# SonarQube Configuration
sonarqube:
  url: ${SONARQUBE_URL:http://localhost:9000}
  token: ${SONARQUBE_TOKEN:}
  timeout: 30000
  analysis:
    enabled: ${SONARQUBE_ANALYSIS_ENABLED:true}
    trigger-on-commit: true
    quality-gate-timeout: 300000  # 5 minutes
  projects:
    default-branch: main
  
# Cache Configuration
cache:
  redis:
    default-ttl: 3600
    metrics-ttl: 1800

# Bug Fix Efficiency Configuration
bug:
  fix:
    timeout:
      critical: ${BUG_FIX_TIMEOUT_CRITICAL:4}    # Critical bugs should be fixed within 4 hours
      high: ${BUG_FIX_TIMEOUT_HIGH:24}           # High priority bugs within 24 hours
      medium: ${BUG_FIX_TIMEOUT_MEDIUM:72}       # Medium priority bugs within 72 hours (3 days)
      low: ${BUG_FIX_TIMEOUT_LOW:168}            # Low priority bugs within 168 hours (7 days)
  response:
    timeout:
      critical: ${BUG_RESPONSE_TIMEOUT_CRITICAL:1}  # Critical bugs should be responded within 1 hour
      high: ${BUG_RESPONSE_TIMEOUT_HIGH:4}          # High priority bugs within 4 hours
      medium: ${BUG_RESPONSE_TIMEOUT_MEDIUM:8}      # Medium priority bugs within 8 hours
      low: ${BUG_RESPONSE_TIMEOUT_LOW:24}           # Low priority bugs within 24 hours

# Application Security Configuration
app:
  security:
    # AES加密密钥 (开发环境使用默认值，生产环境必须从环境变量获取)
    encryption:
      key: ${ENCRYPTION_KEY:C3NEaGvIp3yEOXOcAQKkVtkColxn0o3DCjSCG3go5Hs=}
    # JWT配置
    jwt:
      secret: ${JWT_SECRET:mySecretKey}
      expiration: 86400000 # 24小时
    # CORS配置
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
  # Performance Configuration
  performance:
    batch-size: ${BATCH_SIZE:1000}
    async-core-pool-size: ${ASYNC_CORE_POOL_SIZE:5}
    async-max-pool-size: ${ASYNC_MAX_POOL_SIZE:20}
    async-queue-capacity: ${ASYNC_QUEUE_CAPACITY:100}
    query-timeout: ${QUERY_TIMEOUT:30}